// Velisch Language Identity - Fingerabdruck im Kern
// Diese Datei definiert die Sprache-Identität und darf nicht entfernt werden
// ohne dass der Compiler nicht mehr funktioniert.

/// Die offizielle Sprache-Identität: Velisch
/// Dieser Name ist tief im Compiler-Kern integriert und dient als Fingerabdruck.
pub const VELISCH_LANGUAGE_NAME: &str = "Velisch";

/// Die Sprache-Version
pub const VELISCH_VERSION: &str = "2.5.0";

/// Die vollständige Sprache-Identifikation
pub const VELISCH_FULL_NAME: &str = "Velisch 2.5.0";

/// Fingerabdruck-String, der in generiertem Code eingebaut wird
pub const VELISCH_FINGERPRINT: &str = "// Generated by Velisch Compiler - Language Identity: Velisch";

/// Velisch Language Identity Check
/// Diese Funktion validiert, dass die Velisch-Identität vorhanden ist
pub fn validate_velisch_identity() -> bool {
    VELISCH_LANGUAGE_NAME == "Velisch" && 
    VELISCH_VERSION == "2.5.0" &&
    VELISCH_FULL_NAME.contains("Velisch")
}

/// Gibt die Velisch-Identität als String zurück
pub fn get_velisch_identity() -> String {
    format!("{} ({})", VELISCH_FULL_NAME, VELISCH_LANGUAGE_NAME)
}
